name: web
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main
jobs:
  build:
    name: build
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    # Note: rust-toolchain.toml is needed only during development so it's removed before building.
    - name: Remove rust-toolchain.toml
      uses: JesseTG/rm@v1.0.0
      with:
        path: rust-toolchain.toml

    # Note: .cargo dir is needed only during development so it's removed before building.
    - name: Remove .cargo
      uses: JesseTG/rm@v1.0.0
      with:
        path: .cargo

    - name: Cache cargo folder
      uses: actions/cache@v3
      with:
        key: ${{ github.ref_name }}
        path: |
          ~/.cargo
          ~/.rustup

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        target: wasm32-unknown-unknown

    - name: Build
      shell: bash
      run: ./tools/build-web
